server:
 port: 8081
 
spring:
    application:
      name: 'fornecedor'
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fornecedor?createDatabaseIfNotExist=true&useSSL=false
      username: root
      password: admin
     
     
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka