server:
 port: 8081
 
spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fornecedor?createDatabaseIfNotExist=true&useSSL=false
      username: root
      password: admin
     
     
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
 